from lib import *
print("         \033[42m  DATOS ESTUDIANTES DE ACTUARÍA UTECA     \033[0m ")



alum1 = gradAlum(601049,"Zaira","Durán","35")
alum1.setCalificacion(10)
alum1.setCalificacion(9)
alum1.setCalificacion(8)
alum1.setCalificacion(10)
alum1.setCalificacion(9)
alum1.setDate("01/07/2013")
alum1.setTesis("Los neutrinos saben a jugo de Uva")
print(alum1)
alum2 =gradAlum( 601048, "Frainé", "Durán", "34")
alum2.setCalificacion(6)
alum2.setCalificacion(5)
alum2.setCalificacion(5)
alum2.setCalificacion(4)
alum2.setCalificacion(3)
print(alum2)
alum3 =gradAlum( 100738, "Víctor", "García", "20")
alum3.setCalificacion(8)
alum3.setCalificacion(3)
alum3.setCalificacion(4)
alum3.setCalificacion(5)
alum3.setCalificacion(4)
print(alum3)
alum4 =gradAlum( 100744, "Diego", "López", "18")
alum4.setCalificacion(10)
alum4.setCalificacion(9)
alum4.setCalificacion(8)
alum4.setCalificacion(10)
alum4.setCalificacion(8)
alum4.setDate("01/05/2026")
alum4.setTesis("")
print(alum4)
alum5 =gradAlum( 100692, "Evelyn", "López", "19")
alum5.setCalificacion(10)
alum5.setCalificacion(8)
alum5.setCalificacion(9)
alum5.setCalificacion(5)
alum5.setCalificacion(9)
alum5.setDate("01/05/2027")
alum5.setTesis("")
print(alum5)
alum6 =gradAlum( 99999 , "Daniel", "Rojas", "20")
alum6.setCalificacion(6)
alum6.setCalificacion(5)
alum6.setCalificacion(4)
alum6.setCalificacion(4)
alum6.setCalificacion(3)
print(alum6)
alum7 =gradAlum( 100870, "Mauricio", "Rosas", "20")
alum7.setCalificacion(10)
alum7.setCalificacion(6)
alum7.setCalificacion(10)
alum7.setCalificacion(9)
alum7.setCalificacion(8)
alum7.setDate("01/08/2026")
alum7.setTesis("")
print(alum7)
alum8 =gradAlum( 100437, "Annibal", "Villegas", "20")
alum8.setCalificacion(10)
alum8.setCalificacion(6)
alum8.setCalificacion(10)
alum8.setCalificacion(9)
alum8.setCalificacion(8)
alum8.setDate("01/12/2026")
alum8.setTesis("")
print(alum8)



print("         \033[42m  DATOS ESTUDIANTES DE ACTUARÍA UTECA     \033[0m ")

print("                                                   CALIFICACIONES                                                   ")
print("--------------------------------------|-------------------------------|------------------------------------------------")
print("MATRICULA   | NOMBRE ALUMNO           |   1   |  2  |  3  |  4  |  5  | FINAL | GRAD? |    FECHA   |  TESIS  ")
print("--------------------------------------|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------")
print(f"{alum1.matricula}|\033[1m{alum1.nombre} {alum1.apellido}\033[0m      | {alum1.calificacion[0]} | {alum1.calificacion[1]} | {alum1.calificacion[2]} | {alum1.calificacion[3]} | {alum1.calificacion[4]} | {alum1.prom()} | {alum1.graduacion} | {alum1.fecha} | {alum1.tesis}")
print("--------------------------------------|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------")
print(f"{alum2.matricula}|\033[1m{alum2.nombre} {alum2.apellido}\033[0m      | {alum2.calificacion[0]} | {alum2.calificacion[1]} | {alum2.calificacion[2]} | {alum2.calificacion[3]} | {alum2.calificacion[4]} | {alum2.prom()} | {alum2.graduacion} | {alum2.fecha} | {alum2.tesis}")
print("--------------------------------------|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------")
print(f"{alum3.matricula}|\033[1m{alum3.nombre} {alum3.apellido}\033[0m      | {alum3.calificacion[0]} | {alum3.calificacion[1]} | {alum3.calificacion[2]} | {alum3.calificacion[3]} | {alum3.calificacion[4]} | {alum3.prom()} | {alum3.graduacion} | {alum3.fecha} | {alum3.tesis}")
print("--------------------------------------|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------")
print(f"{alum4.matricula}|\033[1m{alum4.nombre} {alum4.apellido}\033[0m      | {alum4.calificacion[0]} | {alum4.calificacion[1]} | {alum4.calificacion[2]} | {alum4.calificacion[3]} | {alum4.calificacion[4]} | {alum4.prom()} | {alum4.graduacion} | {alum4.fecha} | {alum4.tesis}")
print("--------------------------------------|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------")
print(f"{alum5.matricula}|\033[1m{alum5.nombre} {alum5.apellido}\033[0m      | {alum5.calificacion[0]} | {alum5.calificacion[1]} | {alum5.calificacion[2]} | {alum5.calificacion[3]} | {alum5.calificacion[4]} | {alum5.prom()} | {alum5.graduacion} | {alum5.fecha} | {alum5.tesis}")
print("--------------------------------------|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------")
print(f"{alum6.matricula}|\033[1m{alum6.nombre} {alum6.apellido}\033[0m      | {alum6.calificacion[0]} | {alum6.calificacion[1]} | {alum6.calificacion[2]} | {alum6.calificacion[3]} | {alum6.calificacion[4]} | {alum6.prom()} | {alum6.graduacion} | {alum6.fecha} | {alum6.tesis}")
print("--------------------------------------|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------")
print(f"{alum7.matricula}|\033[1m{alum7.nombre} {alum7.apellido}\033[0m      | {alum7.calificacion[0]} | {alum7.calificacion[1]} | {alum7.calificacion[2]} | {alum7.calificacion[3]} | {alum7.calificacion[4]} | {alum7.prom()} | {alum7.graduacion} | {alum7.fecha} | {alum7.tesis}")
print("--------------------------------------|-------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------")
print(f"{alum8.matricula}|\033[1m{alum8.nombre} {alum8.apellido}\033[0m      | {alum8.calificacion[0]} | {alum8.calificacion[1]} | {alum8.calificacion[2]} | {alum8.calificacion[3]} | {alum8.calificacion[4]} | {alum8.prom()} | {alum8.graduacion} | {alum8.fecha} | {alum8.tesis}")



