from lib import *
print("         \033[46m  DATOS ESTUDIANTES DE ACTUARÍA UTECA     \033[0m ")



alum1 = gradAlum(601049,"Zaira","Durán","35")
alum1.setCalificacion(10)
alum1.setCalificacion(9)
alum1.setCalificacion(8)
alum1.setCalificacion(10)
alum1.setCalificacion(9)
alum1.setGraduacion("Si")
alum1.setDate("01/07/2013")
alum1.setTesis("Los neutrinos saben a jugo de Uva")
print(alum1)
alum2 =gradAlum( 601048, "Frainé", "Durán", "34")
alum2.setCalificacion(6)
alum2.setCalificacion(5)
alum2.setCalificacion(5)
alum2.setCalificacion(4)
alum2.setCalificacion(3)
alum2.setGraduacion("No")
alum2.setDate("N/A")
alum2.setTesis("N/A")
print(alum2)
alum3 =gradAlum( 100738, "Víctor", "García", "20")
alum3.setCalificacion(8)
alum3.setCalificacion(3)
alum3.setCalificacion(4)
alum3.setCalificacion(5)
alum3.setCalificacion(4)
alum3.setGraduacion("No")
alum3.setDate("N/A")
alum3.setTesis("N/A")
print(alum3)
alum4 =gradAlum( 100744, "Diego", "López", "18")
alum4.setCalificacion(10)
alum4.setCalificacion(9)
alum4.setCalificacion(8)
alum4.setCalificacion(10)
alum4.setCalificacion(8)
alum4.setGraduacion("Si")
alum4.setDate("01/05/2026")
alum4.setTesis("El jugo Del Valle es mejor que Boing")
print(alum4)
alum5 =gradAlum( 100692, "Evelyn", "López", "19")
alum5.setCalificacion(10)
alum5.setCalificacion(8)
alum5.setCalificacion(9)
alum5.setCalificacion(5)
alum5.setCalificacion(9)
alum5.setGraduacion("Si")
alum5.setDate("01/05/2027")
alum5.setTesis("¿Por qué sabritas tiene menor producción en las sabritas de habanero?")
print(alum5)
alum6 =gradAlum( 99999 , "Daniel", "Rojas", "20")
alum6.setCalificacion(6)
alum6.setCalificacion(5)
alum6.setCalificacion(4)
alum6.setCalificacion(4)
alum6.setCalificacion(3)
alum6.setGraduacion("No")
alum6.setDate("N/A")
alum6.setTesis("N/A")
print(alum6)
alum7 =gradAlum( 100870, "Mauricio", "Rosas", "20")
alum7.setCalificacion(10)
alum7.setCalificacion(6)
alum7.setCalificacion(10)
alum7.setCalificacion(9)
alum7.setCalificacion(8)
alum7.setGraduacion("Si")
alum7.setDate("01/08/2026")
alum7.setTesis("Teresa :¿ Mala o simplemente con ganas de progresar ?")
print(alum7)
alum8 =gradAlum( 100437, "Annibal", "Villegas", "20")
alum8.setCalificacion(10)
alum8.setCalificacion(5)
alum8.setCalificacion(7)
alum8.setCalificacion(8)
alum8.setCalificacion(10)
alum8.setGraduacion("Si")
alum8.setDate("01/12/2026")
alum8.setTesis("¿Por qué pasar las materias en extraordinario es mejor?")
print(alum8)



print("         \033[42m  DATOS ESTUDIANTES DE ACTUARÍA UTECA     \033[0m ")

print("                                                   CALIFICACIONES                                                   ")
print("--------------------------------------|-------------------------------|------------------------------------------------")
print("MATRICULA   | NOMBRE ALUMNO           |   1   |  2  |  3  |  4  |  5  | FINAL | GRAD? |    FECHA   |  TESIS  ")
print("-----------------------------------------------------------------------------------------------------------------------")
print(f"{alum1.matricula}\t| \033[1m{alum1.nombre} {alum1.apellido}\033[0m\t| {alum1.calificacion[0]}\t| {alum1.calificacion[1]}\t| {alum1.calificacion[2]}\t| {alum1.calificacion[3]}\t| {alum1.calificacion[4]}\t| {alum1.getPromedio()}\t| {alum1.graduacion}\t| {alum1.fecha}\t| {alum1.tesis}")
print("-------------------------------------------------------------------------------------------------------------------------")
print(f"{alum2.matricula}\t| \033[1m{alum2.nombre} {alum2.apellido}\033[0m\t| {alum2.calificacion[0]}\t| \033[31m{alum2.calificacion[1]}\033[0m\t| \033[31m{alum2.calificacion[2]}\033[0m\t| \033[31m{alum2.calificacion[3]}\033[0m\t| \033[31m{alum2.calificacion[4]}\033[0m\t| \033[41m{alum2.getPromedio()}\033[0m\t| {alum2.graduacion}\t| {alum2.fecha}\t| {alum2.tesis}")
print("-------------------------------------------------------------------------------------------------------------------------")
print(f"{alum3.matricula}\t| \033[1m{alum3.nombre} {alum3.apellido}\033[0m\t| {alum3.calificacion[0]}\t| \033[31m{alum3.calificacion[1]}\033[0m\t|  \033[31m{alum3.calificacion[2]}\033[0m\t| \033[31m{alum3.calificacion[3]}\033[0m\t| \033[31m{alum3.calificacion[4]}\033[0m\t| \033[41m{alum3.getPromedio()}\033[0m\t| {alum3.graduacion}\t| {alum3.fecha}\t| {alum3.tesis}")
print("-------------------------------------------------------------------------------------------------------------------------")
print(f"{alum4.matricula}\t| \033[1m{alum4.nombre} {alum4.apellido}\033[0m\t| {alum4.calificacion[0]}\t| {alum4.calificacion[1]}\t| {alum4.calificacion[2]}\t| {alum4.calificacion[3]}\t| {alum4.calificacion[4]}\t| {alum4.getPromedio()}\t| {alum4.graduacion}\t| {alum4.fecha}\t| {alum4.tesis}")
print("-------------------------------------------------------------------------------------------------------------------------")
print(f"{alum5.matricula}\t| \033[1m{alum5.nombre} {alum5.apellido}\033[0m\t| {alum5.calificacion[0]}\t| {alum5.calificacion[1]}\t| {alum5.calificacion[2]}\t| \033[31m{alum5.calificacion[3]}\033[0m\t| {alum5.calificacion[4]}\t| {alum5.getPromedio()}\t| {alum5.graduacion}\t| {alum5.fecha}\t| {alum5.tesis}")
print("-------------------------------------------------------------------------------------------------------------------------")
print(f"{alum6.matricula}\t| \033[1m{alum6.nombre} {alum6.apellido}\033[0m\t| {alum6.calificacion[0]}\t| \033[31{alum6.calificacion[1]}\033[0m\t| \033[31m{alum6.calificacion[2]}\033[0m\t| \033[31m{alum6.calificacion[3]}\033[0m\t| \033[31m{alum6.calificacion[4]}\033[0m\t| \033[41m{alum6.getPromedio()}\033[0m\t| {alum6.graduacion}\t| {alum6.fecha}\t| {alum6.tesis}")
print("-------------------------------------------------------------------------------------------------------------------------")
print(f"{alum7.matricula}\t| \033[1m{alum7.nombre} {alum7.apellido}\033[0m\t| {alum7.calificacion[0]}\t| {alum7.calificacion[1]}\t| {alum7.calificacion[2]}\t| {alum7.calificacion[3]}\t| {alum7.calificacion[4]}\t | {alum7.getPromedio()}\t| {alum7.graduacion}\t| {alum7.fecha}\t| {alum7.tesis}")
print("-------------------------------------------------------------------------------------------------------------------------")
print(f"{alum8.matricula}\t| \033[1m{alum8.nombre} {alum8.apellido}\033[0m\t| {alum8.calificacion[0]}\t| \033[31m{alum8.calificacion[1]}\033[0m\t| {alum8.calificacion[2]}\t| {alum8.calificacion[3]}\t | {alum8.calificacion[4]}\t| {alum8.getPromedio()}\t| {alum8.graduacion}\t| {alum8.fecha}\t| {alum8.tesis}")



